package resume

import (
	"errors"
	"os"
	"os/exec"
	"strings"
	"testing"
)

// requirePDFTool skips rather than fails when poppler is absent.
//
// The unit suite must stay runnable in a container that has no reason to carry
// poppler; the resume-parser image and the dev image both do, and CI runs
// there. A hard failure here would make an unrelated package's tests red on a
// developer's machine for a dependency they do not need.
func requirePDFTool(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("pdftotext"); err != nil {
		t.Skip("pdftotext not installed in this image")
	}
}

// twoColumnCV is a REAL PDF, generated by Chromium from a two-column CV — a
// sidebar of contact details, skills and education beside a body of summary and
// dated roles.
//
// Committed as a binary because the thing under test is what poppler does with
// a real file's glyph positions, which cannot be expressed as a string. It is
// the layout ADR-0007 names as the single most common cause of catastrophic
// parse failure, so it is the one fixture worth having.
func twoColumnCV(t *testing.T) []byte {
	t.Helper()
	b, err := os.ReadFile("testdata/two-column-cv.pdf")
	if err != nil {
		t.Fatalf("fixture: %v", err)
	}
	return b
}

func TestExtractPDF_ReadsATwoColumnCVInReadingOrder(t *testing.T) {
	requirePDFTool(t)

	text, format, err := Extract(twoColumnCV(t))
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if format != FormatPDF {
		t.Fatalf("format = %q, want pdf", format)
	}

	// The whole claim: the sidebar comes out WHOLE and then the body comes out
	// whole, rather than being interleaved line by line. If the columns were
	// merged, "Skills" and the first body heading would land on one line.
	for _, line := range strings.Split(text, "\n") {
		if strings.Contains(line, "Skills") && strings.Contains(line, "Summary") {
			t.Fatalf("columns were interleaved: %q", line)
		}
	}

	for _, want := range []string{"Priya Raman", "priya.raman@example.com", "PostgreSQL", "Razorpay"} {
		if !strings.Contains(text, want) {
			t.Errorf("extracted text is missing %q", want)
		}
	}
}

// The point of the whole phase, measured on the hardest common layout.
func TestParse_TwoColumnPDFYieldsAUsableProfile(t *testing.T) {
	requirePDFTool(t)

	text, format, err := Extract(twoColumnCV(t))
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	r := Parse(text, format, vocab())

	if r.Email != "priya.raman@example.com" {
		t.Errorf("email = %q", r.Email)
	}
	got := skillNames(r)
	for _, want := range []string{"go", "postgresql", "kubernetes", "kafka", "redis"} {
		if !has(got, want) {
			t.Errorf("missing %q from %v", want, got)
		}
	}
	if r.YearsOfExperience == nil {
		t.Fatal("years is nil — the dated roles are in the body column")
	}

	// A two-column CV that parses cleanly must SAY it parsed cleanly. The
	// confidence number is what the UI shows, and under-reporting it would
	// send people to fix a file that is fine.
	if r.Confidence < 0.8 {
		t.Errorf("confidence = %.2f on a cleanly-read two-column CV", r.Confidence)
	}
}

// A PDF with no text layer is a scan. That has a specific, useful diagnosis —
// such a file defeats employer systems too — so it must not be reported as a
// generic failure.
func TestExtractPDF_NoTextLayerIsItsOwnError(t *testing.T) {
	requirePDFTool(t)

	// A structurally valid PDF with one empty page and no text operators.
	empty := []byte("%PDF-1.4\n" +
		"1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n" +
		"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n" +
		"3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj\n" +
		"trailer<</Root 1 0 R>>\n")

	_, _, err := Extract(empty)
	// Either outcome is acceptable and both are honest: poppler may reject the
	// hand-written xref outright, or read it and find no text. What must NOT
	// happen is a successful parse of nothing.
	if err == nil {
		t.Fatal("an empty PDF parsed successfully")
	}
	if !errors.Is(err, ErrNoText) && !strings.Contains(err.Error(), "could not be read") {
		t.Errorf("err = %v; want ErrNoText or a readable failure", err)
	}
}

// Truncated bytes must fail loudly rather than yield partial rubble that then
// silently corrupts every score the user sees.
func TestExtractPDF_TruncatedFileFailsLoudly(t *testing.T) {
	requirePDFTool(t)

	full := twoColumnCV(t)
	_, _, err := Extract(full[:len(full)/2])
	if err == nil {
		t.Fatal("a half-truncated PDF parsed successfully")
	}
}
