/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in account */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The matching profile */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update part of the profile
         * @description Partial by design. An omitted field is left alone, which is what lets
         *     the onboarding wizard save each step without the later steps clobbering
         *     the earlier ones with zero values.
         *
         *     Committing a change also enqueues a re-score in the same transaction, so
         *     "profile saved" and "matches recomputed" cannot diverge.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/v1/me/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish onboarding
         * @description Separate from PATCH /v1/me/profile because "save my progress" and "I am
         *     finished" are different intents with different validation. Per-step
         *     saves skip the completeness check; only this endpoint asserts the
         *     profile can produce meaningful matches, and names the missing fields
         *     when it cannot.
         */
        post: operations["completeOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display preferences */
        get: operations["getPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update display preferences */
        patch: operations["updatePreferences"];
        trace?: never;
    };
    "/v1/me/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in home page */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The job feed
         * @description Public. Discovery does not require an account; a signed-in caller
         *     additionally receives their match score on each item.
         *
         *     Keyset pagination via `cursor`, never OFFSET — at page 40 an OFFSET
         *     query still sorts and discards everything before it.
         */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One posting in full, with its score breakdown
         * @description Public, like the feed — reading a posting needs no account. A signed-in
         *     caller additionally gets `match`, including the five weighted components
         *     and the one-line reason each earned.
         *
         *     Returns 404 for a posting that is no longer live. A role nobody can
         *     apply to is better reported as absent than shown.
         */
        get: operations["getPosting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Counts per filter value
         * @description Lets the UI show "Remote (1,240)" so nobody filters blindly into zero results.
         */
        get: operations["getFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a CV and get back what we understood
         * @description Parses the file and returns a PROPOSAL. Nothing reaches the profile until /apply — a silently wrong skill list corrupts every score afterwards while looking like it worked. The body is the raw file; max 5 MB. PDF, DOCX and plain text are supported. A scanned PDF has no text layer and is refused with advice rather than guessed at.
         */
        post: operations["uploadResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/resume/{id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit the skills the user confirmed
         * @description Writes the CONFIRMED skills with origin='resume' and queues a rescore. Only skills the parse actually proposed are accepted; otherwise this would be an arbitrary add-skill endpoint wearing a resume's name.
         */
        post: operations["applyResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The last 12 weeks of real activity
         * @description Applications sent and statuses that genuinely changed — not logins, not searches, not saves. A grid that lit up because someone opened the page would be measuring attendance. Only days with activity are returned; the client fills the gaps, which it must be able to do anyway for the days before the account existed.
         */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/common": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Starter suggestions for the skill picker
         * @description Served rather than hardcoded in the client: the list existed verbatim in two Svelte files and had already drifted, and it held canonical names, so the chips read "postgresql" and "aws".
         */
        get: operations["getCommonSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Corpus figures, public
         * @description Real numbers for the landing page. Public because "6,804 live postings" is checkable and "thousands of opportunities" is what every job board writes instead. Shares one SQL definition with the dashboard so the two surfaces cannot quote different figures for the same thing.
         */
        get: operations["getMarket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily ingest activity per vendor, public
         * @description Feeds the homepage chart of what the corpus is doing over time. Read from the source_daily rollup rather than from job_postings: this query has no user to filter by, so it would otherwise scan the whole corpus and get slower for every reader as coverage grows. See ADR-0017.
         *
         *     Aggregated to vendor rather than to source. Sixty-five lines is not a chart anybody can read; three to eight is.
         */
        get: operations["getIngestSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every tracked application */
        get: operations["listTracked"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saved/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Save a posting
         * @description Idempotent, and PUT rather than POST for that reason — the button is
         *     easy to double-click and the result must never be two rows. `id` is the
         *     POSTING id here.
         */
        put: operations["saveJob"];
        post?: never;
        /**
         * Remove a saved posting
         * @description Only a bare save is removable. Once an application has advanced,
         *     deleting it would destroy interview history the user cannot
         *     reconstruct; withdrawing is the status change for that. `id` is the
         *     POSTING id.
         */
        delete: operations["unsaveJob"];
        options?: never;
        head?: never;
        /**
         * Advance an application
         * @description `id` is the APPLICATION id here, not the posting id.
         */
        patch: operations["updateTracked"];
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and dependency check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Credentials: {
            /** Format: email */
            email: string;
            /**
             * @description Length is the only rule. Composition requirements push people toward
             *     predictable substitutions; NIST SP 800-63B advises against them.
             *     The upper bound exists so a multi-megabyte password cannot turn
             *     Argon2 into a denial of service.
             */
            password: string;
        };
        SessionInfo: {
            /** Format: date-time */
            expires_at: string;
        };
        Me: {
            /** Format: int64 */
            id: number;
            /** Format: email */
            email: string;
            email_verified: boolean;
        };
        Profile: {
            first_name: string;
            last_name: string;
            current_title: string;
            target_title: string;
            total_yoe: number;
            /**
             * @description Whether experience was ever answered. Zero years is a legitimate
             *     answer — a new graduate has zero — so the count alone cannot
             *     distinguish "none" from "never asked".
             */
            yoe_stated: boolean;
            pref_countries: string[];
            pref_modes: components["schemas"]["WorkMode"][];
            pref_comp_min: number;
            pref_currency: string;
            /** @description Skills the user declared by hand. PATCH replaces this set wholesale, so it must never contain anything inferred. */
            skills: string[];
            /** @description Skills a CV contributed, via POST /v1/me/resume/{id}/apply. Kept separate from `skills` because PATCH replaces that set wholesale — merging them would silently convert every inferred skill into a declared one on the next profile save. */
            readonly resume_skills: string[];
            /** @description Canonical name to how it should be WRITTEN, covering every skill in `skills` and `resume_skills`. The canonical form is the identifier and is deliberately lower-case; rendering it directly is what put "postgresql" and "javascript" on screen as chips. */
            readonly skill_labels: {
                [key: string]: string;
            };
            onboarded: boolean;
        };
        /** @description Every field is optional; an omitted field is left unchanged. */
        ProfileUpdate: {
            first_name?: string;
            last_name?: string;
            current_title?: string;
            target_title?: string;
            total_yoe?: number;
            pref_countries?: string[];
            pref_modes?: components["schemas"]["WorkMode"][];
            pref_comp_min?: number;
            pref_currency?: string;
            skills?: string[];
        };
        /**
         * @description Display settings, stored as JSONB on the user.
         *
         *     There is no `density`. One existed and was removed: it changed row
         *     padding without changing type size or target size, so it did not do the
         *     accessibility job it claimed to. Rows written before the removal still
         *     carry the key and it is preserved untouched, but nothing reads it.
         */
        Preferences: {
            /** @enum {string} */
            theme?: "system" | "light" | "dark";
        };
        /** @enum {string} */
        WorkMode: "remote" | "hybrid" | "onsite";
        /** @enum {string} */
        Band: "strong" | "plausible" | "stretch" | "unlikely";
        Match: {
            score: number;
            band: components["schemas"]["Band"];
            /**
             * @description What the posting asked for that the profile does not have. Shown
             *     with every score: a number the reader cannot interrogate is a number
             *     they cannot overrule.
             */
            missing_skills: string[];
        };
        FeedItem: {
            /** Format: int64 */
            id: number;
            title: string;
            company_name: string;
            company_slug: string;
            location_raw: string;
            city: string | null;
            country: string | null;
            /** @enum {string} */
            mode: "remote" | "hybrid" | "onsite" | "unknown";
            /**
             * Format: uri
             * @description The employer's own ATS URL. Never proxied — we do not claim to apply on anyone's behalf.
             */
            apply_url: string;
            ats_vendor: string;
            /** @description null means NOT DISCLOSED, which is not the same as zero. */
            comp_min: number | null;
            comp_max: number | null;
            comp_currency: string | null;
            comp_period: string | null;
            /** @enum {string|null} */
            comp_source: "structured" | "parsed_text" | null;
            yoe_min: number | null;
            yoe_max: number | null;
            /** @description Below 0.5 the band is unknown, not zero. */
            yoe_confidence: number;
            /** Format: date-time */
            posted_at: string | null;
            /** @description True when the date came from an updated-at rather than a first-published field. */
            posted_at_is_estimate: boolean;
            /** Format: date-time */
            first_seen_at: string;
            /** @description null means the vendor does not expose it — "unknown", never "no AI". */
            ai_screening_disclosed: boolean | null;
            ai_opt_out_url: string | null;
            parse_confidence: number;
            must_have_skills: string[];
            nice_to_have_skills: string[];
            /** @description Absent for anonymous callers and for postings not yet scored. */
            match?: components["schemas"]["Match"];
            saved: boolean;
        };
        /** @description One posting in full. Extends the feed shape with the description and the complete score reasoning. */
        Posting: {
            /** Format: int64 */
            id: number;
            title: string;
            company_name: string;
            company_slug: string;
            location_raw: string;
            mode: string;
            /** Format: uri */
            apply_url: string;
            ats_vendor: string;
            /** @description The employer's own markup, sanitised at ingest. */
            description_html: string;
            comp_min: number | null;
            comp_max: number | null;
            comp_currency: string | null;
            comp_period: string | null;
            comp_source: string | null;
            yoe_min: number | null;
            yoe_max: number | null;
            yoe_confidence: number;
            /** Format: date-time */
            posted_at: string | null;
            posted_at_is_estimate: boolean;
            /** Format: date-time */
            first_seen_at: string;
            ai_screening_disclosed: boolean | null;
            ai_disclaimer: string | null;
            ai_opt_out_url: string | null;
            parse_confidence: number;
            must_have_skills: string[];
            nice_to_have_skills: string[];
            saved: boolean;
            match?: components["schemas"]["PostingMatch"];
        };
        PostingMatch: {
            score: number;
            band: components["schemas"]["Band"];
            /**
             * @description Below 1 when part of the picture was unreadable — a posting whose
             *     requirements we could not extract, or a resume we struggled with.
             */
            confidence: number;
            missing_skills: string[];
            components: components["schemas"]["MatchComponent"][];
            /** Format: date-time */
            computed_at: string;
        };
        /**
         * @description One weighted part of a score with the reason it earned what it did.
         *     Stored as the scorer wrote it and replayed verbatim, so the reasons shown
         *     are the ones that produced this score rather than a recomputation that
         *     could disagree with it.
         */
        MatchComponent: {
            /** @enum {string} */
            name: "skills" | "experience" | "location" | "compensation" | "freshness" | "parse";
            score: number;
            max: number;
            /** @description Plain-English reason, generated by the scorer. */
            detail: string;
            /**
             * @description True when the component ABSTAINED — the posting did not disclose
             *     enough to judge it. An abstaining component is excluded from both
             *     numerator and denominator, so it never drags a score down. This is
             *     not the same as scoring zero.
             */
            neutral: boolean;
            matched?: string[];
            missing?: string[];
        };
        FeedPage: {
            data: components["schemas"]["FeedItem"][];
            next_cursor?: string;
            has_more: boolean;
            /**
             * Format: date-time
             * @description When the viewer's previous visit ended. Absent for anonymous viewers
             *     and for a first visit — where everything would be new, and a page on
             *     which every row is flagged flags nothing.
             *
             *     Distinct from `posted_within=24h`: this is about **you**, that is
             *     about the market. A visit boundary is a gap of 30 minutes.
             */
            since_last_visit?: string;
        };
        Facets: {
            modes: {
                [key: string]: number;
            };
            countries: {
                [key: string]: number;
            };
            vendors: {
                [key: string]: number;
            };
            /** @description Counts per experience band, keyed exactly as the ?yoe= parameter takes them, so the client never translates between what it shows and what it sends. `unstated` is a band of its own — a posting with no stated range is not evidence of being junior or senior. */
            yoe: {
                [key: string]: number;
            };
            /** @description Counts per salary floor, keyed as ?comp_min= takes them. CUMULATIVE, not disjoint: "150000" is every posting paying at least that, which is what the chip claims and therefore what its count must mean. */
            comp: {
                [key: string]: number;
            };
            /** @description Postings publishing no salary. Surfaced because a salary filter silently excludes them, and about a fifth of the market is in here. */
            comp_undisclosed: number;
            total: number;
        };
        Dashboard: {
            greeting: string;
            matches: components["schemas"]["MatchSummary"];
            pipeline: components["schemas"]["PipelineStage"][];
            needs_reply: components["schemas"]["ActionItem"][];
            top_matches: components["schemas"]["DashboardJob"][];
            market: components["schemas"]["MarketSummary"];
            strength: components["schemas"]["Strength"];
        };
        /**
         * @description How complete the profile is, and what completing it would change. Each
         *     item names the scoring component it feeds — "60% complete" on its own
         *     tells a user nothing about whether to care.
         */
        Strength: {
            percent: number;
            items: components["schemas"]["StrengthItem"][];
        };
        StrengthItem: {
            field: string;
            label: string;
            done: boolean;
            /** @description What this field changes about matching. */
            why: string;
        };
        MatchSummary: {
            strong: number;
            plausible: number;
            new_today: number;
            /** @description How many postings were ranked to produce these counts. Replaces `scored`: scores are computed per request rather than stored, so there is no set of "scored" rows to count. See ADR-0016. */
            considered: number;
        };
        PipelineStage: {
            status: components["schemas"]["ApplicationStatus"];
            label: string;
            count: number;
        };
        ActionItem: {
            /** Format: int64 */
            id: number;
            company_name: string;
            role_title: string;
            status: components["schemas"]["ApplicationStatus"];
            days_since: number;
            next_action?: string;
            /** Format: date-time */
            next_action_at?: string | null;
        };
        DashboardJob: {
            /** Format: int64 */
            id: number;
            title: string;
            company_name: string;
            location: string;
            mode: string;
            score: number;
            band: components["schemas"]["Band"];
            missing_skills: string[];
            /** Format: date-time */
            posted_at: string;
            /** Format: uri */
            apply_url: string;
            saved: boolean;
        };
        ResumeUpload: {
            /** Format: int64 */
            id: number;
            label: string;
            /** @enum {string} */
            format: "docx" | "pdf" | "text" | "unknown";
            /** @description How much of the document's expected structure we recovered, 0-1. Shown to the user, never hidden — a reader deciding on an incomplete parse should know it is incomplete. */
            confidence: number;
            email?: string;
            phone?: string;
            links?: string[];
            skills: components["schemas"]["ResumeSkill"][];
            /** @description null means we could not tell. It is NOT zero — those are opposite claims about a candidate. */
            years_of_experience: number | null;
            diagnostics: components["schemas"]["ResumeDiagnostic"][];
            /** @description How many of these the profile does not already have. */
            new_skills: number;
            /** Format: date-time */
            created_at: string;
        };
        ResumeSkill: {
            /** @description The identifier, lower-case. Sent back on apply. */
            canonical: string;
            /** @description How to write it on screen. Showing the canonical directly rendered "postgresql" and "node.js" as chips. */
            label: string;
            /**
             * @description Where in the CV it was found. A skill described inside a role is a stronger claim than one merely listed, and the UI shows the difference.
             * @enum {string}
             */
            evidence: "experience" | "projects" | "skills" | "summary" | "education" | "other" | "unlabelled";
            years?: number;
            /** @description True when the profile already has this skill. */
            known: boolean;
        };
        ResumeDiagnostic: {
            code: string;
            message: string;
            /** @enum {string} */
            severity: "blocking" | "warning";
        };
        ResumeApply: {
            /** @description The skills the user CONFIRMED, not the ones we proposed. An unchecked skill is never written; corrections always win. */
            skills: string[];
            /** @description Opt-in separately, because it overwrites a field the user may have set by hand. */
            set_years?: boolean;
        };
        Activity: {
            days: components["schemas"]["ActivityDay"][];
            /**
             * Format: date
             * @description First day of the window, a Monday. The server decides the shape so it cannot drift across a midnight boundary in the browser.
             */
            from: string;
            /** Format: date */
            to: string;
            /** @description Sum over the window. A plain count, never a streak — this is a record of what happened, not a target to hit. */
            total: number;
        };
        ActivityDay: {
            /** Format: date */
            day: string;
            count: number;
        };
        SkillSuggestion: {
            /** @description The identifier, lower-case. */
            canonical: string;
            /** @description How to write it on screen. */
            label: string;
        };
        MarketSummary: {
            live_postings: number;
            companies: number;
            added_this_week: number;
            remote_share: number;
        };
        IngestSeries: {
            /** @description Every day in the window, including days with no activity. A gap and a zero mean different things on a chart and the client cannot tell them apart unless the zero is present. */
            days: string[];
            series: components["schemas"]["IngestVendorSeries"][];
        };
        IngestVendorSeries: {
            vendor: string;
            /** @description Postings first seen on each day. The flow. */
            new: number[];
            /** @description Postings still live at the end of each day. The level. */
            live: number[];
        };
        /** @enum {string} */
        ApplicationStatus: "saved" | "applied" | "referred" | "recruiter_screen" | "hm_screen" | "onsite" | "offer" | "rejected" | "ghosted" | "withdrawn";
        /** @enum {string} */
        ApplicationChannel: "careers_page" | "job_board" | "referral" | "cold_email" | "recruiter_inbound" | "other";
        TrackedItem: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            posting_id: number | null;
            company_name: string;
            role_title: string;
            status: components["schemas"]["ApplicationStatus"];
            apply_url?: string;
            note?: string;
            next_action?: string;
            /** Format: date-time */
            next_action_at?: string | null;
            /** Format: date-time */
            applied_at?: string | null;
            /** Format: date-time */
            updated_at: string;
            /**
             * @description Days since anything last happened on this application. A **fact**,
             *     reported without interpretation.
             *
             *     Nothing sets a terminal status on the user's behalf. An earlier
             *     version moved applications to `ghosted` after 21 days, which
             *     asserted an employer's intent from silence — and from silence in our
             *     own records, which contain only what the user chose to log.
             */
            days_since_activity: number;
        };
        TrackedUpdate: {
            status?: components["schemas"]["ApplicationStatus"];
            channel?: components["schemas"]["ApplicationChannel"];
            note?: string;
            next_action?: string;
            /** Format: date */
            next_action_at?: string;
        };
        FieldError: {
            field: string;
            code: string;
            message: string;
        };
        /** @description RFC 9457. */
        ProblemDetail: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            fields?: components["schemas"]["FieldError"][];
            /** @description Correlates a user-visible error with its server logs and traces. */
            trace_id?: string;
        };
    };
    responses: {
        /** @description RFC 9457 problem detail */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Created; the session cookie is set on this response. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out; the session cookie is cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description The profile after the update. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Onboarded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Preferences"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description Free-text search */
                q?: string;
                /** @description Comma-separated ISO 3166-1 alpha-2 codes */
                country?: string;
                /** @description Comma-separated: remote, hybrid, onsite */
                mode?: string;
                yoe?: number;
                yoe_stretch?: boolean;
                comp_min?: number;
                comp_currency?: string;
                comp_disclosed_only?: boolean;
                /** @description 1d, 7d, 30d or any */
                posted_within?: string;
                /** @description Comma-separated; ALL must match */
                skills?: string;
                vendor?: string;
                /**
                 * @description Comma-separated match bands — strong, plausible, stretch, unlikely.
                 *
                 *     **Requires an authenticated caller.** A band states how well a role
                 *     fits one specific person, so it cannot be honoured without a profile;
                 *     an anonymous request carrying it gets a 400 rather than being
                 *     silently ignored.
                 *
                 *     Filtering here also excludes postings the matcher has not scored yet,
                 *     since an unscored posting has no band. That is intended for a
                 *     deliberate "show me strong fits" request.
                 */
                band?: string;
                sort?: "newest" | "comp" | "match";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPage"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    getPosting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Posting"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getFacets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
        };
    };
    uploadResume: {
        parameters: {
            query?: {
                /** @description Optional name for this CV. Defaults to the upload date. */
                label?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Parsed. Review before applying. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUpload"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    applyResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeApply"];
            };
        };
        responses: {
            /** @description Applied; rescoring queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        applied: number;
                        rescoring: boolean;
                    };
                };
            };
            /** @description No such resume for this user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
        };
    };
    getCommonSkills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSuggestion"][];
                };
            };
        };
    };
    getMarket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketSummary"];
                };
            };
        };
    };
    getIngestSeries: {
        parameters: {
            query?: {
                /** @description Window length, ending today. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestSeries"];
                };
            };
        };
    };
    listTracked: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["TrackedItem"][];
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    saveJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedItem"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    unsaveJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Problem"];
        };
    };
    updateTracked: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackedUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Degraded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
